version: '3.8'

services:
  db-backend:
    container_name: ${CONTAINER_NAME}
    image: postgres:13.13-alpine3.18
    #    restart: always
    platform: linux/amd64
    env_file:
      - ${env}/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data/

volumes:
  db_data:
