version: '3.8'

services:
  api-services:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../../../
      dockerfile: devops/services/base/Dockerfile
      args:
        SERVICE_NAME: ${SERVICE_NAME}
    image: ${IMAGE_NAME}
    platform: linux/amd64
#    restart: always
    command: /start.sh
    volumes:
      - ${MOUNT}:/app
    ports:
      - ${GUEST_PORT}:${HOST_PORT}
